In [1]:
import os
import scipy.io
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_context('paper', font_scale=1.1)
import pandas as pd
import warnings
import sys

warnings.filterwarnings('ignore')
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
DirectoryName = '/Users/seetha/Box Sync/MultiDayData/Data/'
SaveFolder = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/'

In [3]:
os.path.normpath(DirectoryName + os.sep + os.pardir)

'/Users/seetha/Box Sync/MultiDayData'

In [4]:
from create_data import GetData as gd

In [5]:
na = gd(DirectoryName, SaveFolder)

In [6]:
taskstocompare = 'Task2'
na.get_adjacency_matrix(taskstocompare)

NR34
Number of pfs 256 Number of single pfs 223
25
Analysing..223 cells
Corr matrix min -0.7 and max 1.0
N edges: 9676
NR34_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (223, 6)
CFC17
Number of pfs 234 Number of single pfs 195
22
Analysing..195 cells
Corr matrix min -0.7 and max 1.0
N edges: 6124
CFC17_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (195, 6)
NR32
Number of pfs 160 Number of single pfs 135
25
Analysing..135 cells
Corr matrix min -0.8 and max 1.0
N edges: 3508
NR32_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (135, 6)
CFC16
Number of pfs 453 Number of single pfs 408
17
Analysing..408 cells
Corr matrix min -0.9 and max 1.0
N edges: 35728
CFC16_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (408, 6)
CFC18
Number of pfs 511 Number of single pfs 458
16
Analysing..458 cells
Corr matrix min -0.9 and max 1.0
N edges: 44984
CFC18_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (458, 6)


In [7]:
taskstocompare = 'Task4'
na.get_adjacency_matrix(taskstocompare, basetask='Task3')

NR34
Number of pfs 480 Number of single pfs 353
8
Analysing..353 cells
Corr matrix min -0.9 and max 1.0
N edges: 28643
NR34_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (353, 6)
CFC17
Number of pfs 230 Number of single pfs 169
18
Analysing..169 cells
Corr matrix min -0.8 and max 1.0
N edges: 5031
CFC17_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (169, 6)
NR32
Number of pfs 240 Number of single pfs 194
10
Analysing..194 cells
Corr matrix min -0.8 and max 1.0
N edges: 7048
NR32_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (194, 6)
CFC16
Number of pfs 473 Number of single pfs 420
13
Analysing..420 cells
Corr matrix min -0.7 and max 0.9
N edges: 37725
CFC16_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (420, 6)
CFC18
Number of pfs 669 Number of single pfs 557
9
Analysing..557 cells
Corr matrix min -0.8 and max 1.0
N edges: 72509
CFC18_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (557, 6)


In [8]:
taskstocompare = 'Task5'
na.get_adjacency_matrix(taskstocompare, basetask='Task1')

NR34
Number of pfs 256 Number of single pfs 223
25
Analysing..223 cells
Corr matrix min -0.7 and max 0.8
N edges: 9926
NR34_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (223, 6)
CFC17
Number of pfs 234 Number of single pfs 195
22
Analysing..195 cells
Corr matrix min -0.7 and max 1.0
N edges: 5068
CFC17_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (195, 6)
NR32
Number of pfs 160 Number of single pfs 135
25
Analysing..135 cells
Corr matrix min -0.9 and max 1.0
N edges: 3734
NR32_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (135, 6)
CFC16
Number of pfs 453 Number of single pfs 408
17
Analysing..408 cells
Corr matrix min -0.9 and max 1.0
N edges: 30064
CFC16_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (408, 6)
CFC18
Number of pfs 511 Number of single pfs 458
16
Analysing..458 cells
Corr matrix min -0.8 and max 1.0
N edges: 42871
CFC18_placecellparams_df.csv
[1 2 3 4 5 6 7 8]
Nodes (458, 6)
