In [2]:
import os
import scipy.io
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_context('paper', font_scale=1.1)
import pandas as pd
import warnings
import sys

warnings.filterwarnings('ignore')
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from create_data_for_gephi import GetData as gd

In [4]:
DirectoryName = '/Users/seetha/Box Sync/MultiDayData/Data/'
CombinedFolderName = '/Users/seetha/Box Sync/MultiDayData/PlaceCellResultsAll/'
SaveFolder = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/'

In [5]:
na = gd(DirectoryName, CombinedFolderName)

In [28]:
taskstocompare = 'Task5'

na.get_adjacency_matrix(taskstocompare, basetask='Task1',
                                   reliability_type='High', subsample=False, shuffle_flag=False,
                                   SaveFolder=os.path.join(SaveFolder, 'Highreliability'))

NR34
Analysing..99 cells
Corr matrix min -0.8 and max 1.0
N edges: 2159
[1 2 3 4 5 6 7 8]
Nodes (99, 6)
CFC17
Analysing..145 cells
Corr matrix min -0.5 and max 1.0
N edges: 2962
[1 2 3 4 5 6 7 8]
Nodes (145, 6)
NR32
Analysing..67 cells
Corr matrix min -0.7 and max 1.0
N edges: 926
[1 2 3 4 5 6 7 8]
Nodes (67, 6)
CFC16
Analysing..51 cells
Corr matrix min -0.6 and max 1.0
N edges: 635
[1 2 3 4 5 6 7 8]
Nodes (51, 6)
CFC18
Analysing..171 cells
Corr matrix min -0.8 and max 1.0
N edges: 7077
[1 2 3 4 5 6 7 8]
Nodes (171, 6)


In [29]:
taskstocompare = 'Task5'
group1, group2 = na.get_adjacency_matrix(taskstocompare, basetask='Task1', reliability_type='Low',
                        subsample=False,
                        SaveFolder=os.path.join(SaveFolder, 'Lowreliability'))

NR34
Analysing..193 cells
Corr matrix min -0.6 and max 0.9
N edges: 7723
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (193, 6)
CFC17
Analysing..127 cells
Corr matrix min -0.7 and max 1.0
N edges: 1748
[1 2 3 4 5 6 7 8]
Nodes (127, 6)
NR32
Analysing..116 cells
Corr matrix min -0.7 and max 1.0
N edges: 2103
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (116, 6)
CFC16
Analysing..425 cells
Corr matrix min -0.7 and max 0.9
N edges: 36984
[]
WHAT
[]
WHAT
[]
WHAT
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (425, 6)
CFC18
Analysing..328 cells
Corr matrix min -0.7 and max 0.9
N edges: 22588
[1 2 3 4 5 6 7 8]
Nodes (328, 6)


TypeError: cannot unpack non-iterable NoneType object

In [ ]:
fs, ax = plt.subplots(1, 2)
na.plot_graph_factors_bytrack_iterated(ax[0], by_location_highrel, column_name='Degree')
na.plot_graph_factors_bytrack_iterated(ax[0], by_location_lowrel, column_name='Degree')
na.plot_graph_factors_bytrack_iterated(ax[1], by_location_highrel, column_name='Clustering')
na.plot_graph_factors_bytrack_iterated(ax[1], by_location_lowrel, column_name='Clustering')
sns.despine(fs)

## Calculate weighted degrees

In [ ]:
from analysegraph import PlotData as pld

### Task1_Task2

In [ ]:
foldername = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/WeightedDegree/Task1_Task2/'
SaveFigureFolder = '/Users/seetha/Box Sync/MultiDayData/MultiDayPaper/Figures/FigurepanelsPDF/NetworkAnalysis/'
g = pld(foldername)
column_name = 'Weighted Degree'

In [ ]:
df_high = g.concat_files(reliability_flag='high')
high_group = g.group_df_bylocation(df_high, column_name=column_name)
high_group

In [ ]:
df_low = g.concat_files(reliability_flag='low')
low_group = g.group_df_bylocation(df_low, column_name=column_name)

In [ ]:
fs, ax = plt.subplots(1, 2, gridspec_kw={'width_ratios':[2, 1]})
g.plot_column(ax, df_high, high_group, df_low, low_group, column_name=column_name)
sns.despine(fs)
fs.set_size_inches((3, 2))
# fs.savefig(os.path.join(SaveFigureFolder, '%s_fulllowrelcells_Task1.pdf'%column_name), bbox_inches='tight')

## Task3_Task4

In [ ]:
foldername = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/WeightedDegree/Task3_Task4/'
g = pld(foldername)

In [ ]:
df_high = g.concat_files(reliability_flag='high')
high_group = g.group_df_bylocation(df_high, column_name=column_name)

In [ ]:
df_low = g.concat_files(reliability_flag='low')
low_group = g.group_df_bylocation(df_low, column_name=column_name)

In [ ]:
fs, ax = plt.subplots(1, 2, gridspec_kw={'width_ratios':[2, 1]})
g.plot_column(ax, df_high, high_group, df_low, low_group, column_name=column_name)
sns.despine(fs)
fs.set_size_inches((3, 2))
# fs.savefig(os.path.join(SaveFigureFolder, '%s_fulllowrelcells_Task3.pdf'%column_name), bbox_inches='tight')

## Subselect

### Task1_Task2

In [ ]:
foldername = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/WeightedDegree/Task1_Task2/'
g = pld(foldername)
column_name = 'Weighted Degree'

In [ ]:
df_high = g.concat_files(reliability_flag='high')
high_group = g.select_graph_node_bylocation(df_high, column_name=column_name)

In [ ]:
df_low = g.concat_files(reliability_flag='low')
low_group = g.select_graph_node_bylocation(df_low, column_name=column_name)

In [ ]:
fs, ax = plt.subplots(1, 2, gridspec_kw={'width_ratios':[2, 1]})
g.plot_column(ax, df_high, high_group, df_low, low_group, column_name=column_name)
sns.despine(fs)
fs.set_size_inches((3, 2))
fs.savefig(os.path.join(SaveFigureFolder, '%s_subsampled_Task1.pdf'%column_name), bbox_inches='tight')

### Task3_Task4

In [ ]:
foldername = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/Weighted_degree/Task3_Task4/'
g = pld(foldername)

In [ ]:
df_high = g.concat_files(reliability_flag='high')
high_group = g.select_graph_node_bylocation(df_high, column_name=column_name)

In [ ]:
df_low = g.concat_files(reliability_flag='low')
low_group = g.select_graph_node_bylocation(df_low, column_name=column_name)

In [ ]:
fs, ax = plt.subplots(1, 2, gridspec_kw={'width_ratios':[2, 1]})
g.plot_column(ax, df_high, high_group, df_low, low_group, column_name=column_name)
sns.despine(fs)
fs.set_size_inches((3, 2))
fs.savefig(os.path.join(SaveFigureFolder, '%s_subsampled_Task3.pdf'%column_name), bbox_inches='tight')

## Normalize

In [ ]:
foldername = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/WeightedDegree/Task1_Task2/'
SaveFigureFolder = '/Users/seetha/Box Sync/MultiDayData/MultiDayPaper/Figures/FigurepanelsPDF/NetworkAnalysis/'
g = pld(foldername)
column_name = 'Weighted Degree'

In [ ]:
df_high = g.concat_files(reliability_flag='high')
high_group = g.normalize_graph_node_bylocation(df_high, column_name=column_name)
high_group

In [ ]:
df_low = g.concat_files(reliability_flag='low')
low_group = g.normalize_graph_node_bylocation(df_low, column_name=column_name)

In [ ]:
fs, ax = plt.subplots(1, 2, gridspec_kw={'width_ratios':[2, 1]})
g.plot_normalized_column(ax, df_high, high_group, df_low, low_group, column_name=column_name)
sns.despine(fs)
fs.set_size_inches((3, 2))
# fs.savefig(os.path.join(SaveFigureFolder, '%s_subsampledlowrel_normalized_Task1.pdf'%column_name), bbox_inches='tight')

## Task3_Task4

In [ ]:
foldername = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/WeightedDegree/Task3_Task4/'
g = pld(foldername)

In [ ]:
df_high = g.concat_files(reliability_flag='high')
high_group = g.normalize_graph_node_bylocation(df_high, column_name=column_name)

In [ ]:
df_low = g.concat_files(reliability_flag='low')
low_group = g.normalize_graph_node_bylocation(df_low, column_name=column_name)

In [ ]:
fs, ax = plt.subplots(1, 2, gridspec_kw={'width_ratios':[2, 1]})
g.plot_normalized_column(ax, df_high, high_group, df_low, low_group, column_name=column_name)
sns.despine(fs)
fs.set_size_inches((3, 2))
fs.savefig(os.path.join(SaveFigureFolder, '%s_subsampledlowrel_normalized_Task3.pdf'%column_name), bbox_inches='tight')