In [1]:
import os
import scipy.io
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_context('paper', font_scale=1.1)
import pandas as pd
import warnings
import sys

warnings.filterwarnings('ignore')
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
from create_data_for_gephi import GetData as gd

In [3]:
DirectoryName = '/Users/seetha/Box Sync/MultiDayData/Data/'
CombinedFolderName = '/Users/seetha/Box Sync/MultiDayData/PlaceCellResultsAll/'
SaveFolder = '/Users/seetha/Box Sync/MultiDayData/NetworkAnalysis/Allcells/'

In [4]:
na = gd(DirectoryName, CombinedFolderName)

In [6]:
taskstocompare = 'Task2'

na.get_adjacency_matrix(taskstocompare, basetask='Task1',
                                   reliability_type='All', subsample=False, shuffle_flag=False,
                                   SaveFolder=os.path.join(SaveFolder))

NR34
Analysing..292 cells
Corr matrix min -0.7 and max 1.0
N edges: 18599
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (292, 6)
CFC17
Analysing..272 cells
Corr matrix min -0.6 and max 1.0
N edges: 11335
[1 2 3 4 5 6 7 8]
Nodes (272, 6)
NR32
Analysing..183 cells
Corr matrix min -0.7 and max 1.0
N edges: 7058
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (183, 6)
CFC16
Analysing..476 cells
Corr matrix min -0.8 and max 1.0
N edges: 51746
[]
WHAT
[]
WHAT
[]
WHAT
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (476, 6)
CFC18
Analysing..499 cells
Corr matrix min -0.8 and max 1.0
N edges: 47857
[1 2 3 4 5 6 7 8]
Nodes (499, 6)


In [7]:
taskstocompare = 'Task4'

na.get_adjacency_matrix(taskstocompare, basetask='Task3',
                                   reliability_type='All', subsample=False, shuffle_flag=False,
                                   SaveFolder=os.path.join(SaveFolder))

NR34
Analysing..581 cells
Corr matrix min -0.8 and max 1.0
N edges: 79516
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (581, 6)
CFC17
Analysing..286 cells
Corr matrix min -0.6 and max 1.0
N edges: 12702
[1 2 3 4 5 6 7 8]
Nodes (286, 6)
NR32
Analysing..271 cells
Corr matrix min -0.7 and max 1.0
N edges: 15207
[]
WHAT
[]
WHAT
[]
WHAT
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (271, 6)
CFC16
Analysing..523 cells
Corr matrix min -0.7 and max 0.9
N edges: 63373
[]
WHAT
[]
WHAT
[]
WHAT
[1 2 3 4 5 6 7 8]
Nodes (523, 6)
CFC18
Analysing..694 cells
Corr matrix min -0.8 and max 1.0
N edges: 117782
[1 2 3 4 5 6 7 8]
Nodes (694, 6)
